### PR TITLE
Add support for livestreams

### PR DESCRIPTION
**Pull request by andreasgan**
Hi, thanks for this plugin!
Here's a small change that adds support for livestreams.

### CODE REVIEW

**Comment by andreasgan** [comment]
The build is failing because of wrong node version so not related

**Comment by jthomerson** [comment]
@andreasgan can you please edit the pull request so that maintainers can push to the branch? I'm not allowed to fix up your commits because that box isn't checked

Or, please squash the last commit onto the first commit, which is what I was trying to do.

**Comment by andreasgan** [comment]
Because the fork is in an organization, I can't allow you to edit so I had to add you as a collaborator to the fork.
https://github.com/isaacs/github/issues/1681

**Comment by andreasgan** [comment]
But I did the squash

**Review by jthomerson — APPROVED** [review]

**Comment by jthomerson** [comment]
@andreasgan thanks! I did not realize that problem with organizations and PR's. Learned something new. But since you squashed, that's all I needed. You can remove my access to the org.

@yokuze this looks fine to me. Can you take a quick look and see if you have any concerns?

**Comment by yokuze** [comment]
> @yokuze this looks fine to me. Can you take a quick look and see if you have any concerns?

@jthomerson This looks fine to me. It's been a while since I've looked at live stream support in Video.js so I can't definitively say this is _all_ that's needed, but I don't have any concerns with this change.

**Comment by jthomerson** [comment]
@andreasgan published in @silvermine/videojs-chromecast@1.3.0

**Pull request merged**
